### ISSUE TITLE
TLS requirement not clear for docker compose local deployment

### ISSUE THREAD

**Issue by JMuff22** [waldur/waldur-docs#3]
Hi, 

Following the instructions for a [local deployment using docker compose](https://docs.waldur.com/admin-guide/deployment/docker-compose/)  it is not immediately clear that TLS is needed. 

The example `.env` provided specifies that

```
# (Required) Choose SSL certificate type (tls config value in Caddy)
# 1. email (Specify your email) - auto generate let's encrypt SSL certificates for your domain
# 2. "internal" - use self-signed certificates for dev environments
# 3. path_to_cert.crt path_to_key.key - use custom certificate. Be sure to pass them in docker-compose.yml
TLS=certs@waldur.com
```

And then the instructions specify to access at http://localhost/ .  To access at http://localhost/ `TLS=internal` is needed which is described later on, on the same page. 

Is there a reason why the default example argument is to setup Let's Encrypt certs?

P.S Great project.

**Comment by yefimg** [comment]
Hi @JMuff22 !

Thank you for noticing this!

Default TLS mode has been changed to "internal" and http:// changed to https://.
That should make the installation work locally out of the box.
